version: '3'
services:
  receiver:
    build: ./receiver
    ports:
     - "3000:3000"
  task-queue:
    image: "rabbitmq:3.7.7"
    ports:
      -"5672:5672"
  storage:
    build: ./storage
  storage-db:
    image: "cassandra:3.11.3"
